apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Apache
  template:
    metadata:
      labels:
        app: Apache
    spec:
      containers:
        - name: apache-container
          image: treehouses/php-apache 
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://shopping-cart-backend-service:3005  
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: Apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
